/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ma.aui.sse.paradigms.extensibility.windows;

import static ma.aui.sse.paradigms.extensibility.windows.Node.FOLDER;
import static ma.aui.sse.paradigms.extensibility.windows.Node.FILE;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        FileSystem fileSystem = new FileSystem();

        fileSystem.create(new Node("/some/path", FOLDER));
        fileSystem.create(new Node("/other/path", FOLDER));

        Window blueW = new Window("Blue");
        blueW.setCurrentPath("/some/path");
        Window redW = new Window("Red");
        redW.setCurrentPath("/other/path");

        fileSystem.subscribe(blueW);
        fileSystem.subscribe(redW);

        Node node1 = new Node("/some/path/file1", FILE);
        Node node2 = new Node("/other/path/file2", FILE);

        fileSystem.create(node1);
        fileSystem.create(node2);
        System.out.println();

        blueW.setCurrentPath("/other/path");

        fileSystem.delete(node2);
        System.out.println();
        fileSystem.create(node2);
        System.out.println();

        fileSystem.unsubscribe(redW);
        fileSystem.delete(node2);
    }
}
