/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ma.aui.sse.paradigms.scalability.rating;

import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.SparkConf;

import java.util.List;

public class Driver {

    private static String MASTER_URL = "spark://10.10.10.10:7070";

    public static void main(String[] args) {
        SparkConf conf = new SparkConf().setAppName("Rating").setMaster(MASTER_URL);
        JavaSparkContext sc = new JavaSparkContext(conf);

        List<Rating> ratings = null; // To do

        JavaRDD<Rating> ratingRDD = sc.parallelize(ratings);

    }
}
