# coding: utf-8

"""
    Calculator OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.calculator_api import CalculatorApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCalculatorApi(unittest.TestCase):
    """CalculatorApi unit test stubs"""

    def setUp(self):
        self.api = CalculatorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add(self):
        """Test case for add

        """
        pass

    def test_compute_all(self):
        """Test case for compute_all

        """
        pass

    def test_divide(self):
        """Test case for divide

        """
        pass

    def test_multiply(self):
        """Test case for multiply

        """
        pass

    def test_subtract(self):
        """Test case for subtract

        """
        pass


if __name__ == '__main__':
    unittest.main()
